"""Renomear coluna na tabela consumo

Revision ID: cf82d8d10f07
Revises: 
Create Date: 2024-09-11 15:57:43.146333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf82d8d10f07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumo', schema=None) as batch_op:
        batch_op.alter_column(
            'consumo', 
            'produto_id',new_column_name='produto_acabado_id'
        )
        batch_op.drop_constraint('fk_produto_id', 'consumo', type_='foreignkey')
        batch_op.create_foreign_key(
            'fk_produto_acabado',
            'consumo', 
            'produto_acabado', 
            ['produto_acabado_id'], 
            ['id']
        )
        batch_op.drop_column('produto_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('produto_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'produto_acabado', ['produto_id'], ['id'])
        batch_op.drop_column('produto_acabado_id')

    # ### end Alembic commands ###
